### ISSUE TITLE
Research NLP-Neural Networks

### ISSUE THREAD

**Issue by ayaanzhaque** [ayaanzhaque/SuiSense#1]
Figure out how we can build an industry-standard NLP model that we can use

**Comment by ayaanzhaque** [comment]
http://jalammar.github.io/illustrated-bert/
We can just use BERT and retrain it on our own data

**Comment by ayaanzhaque** [comment]
well we cant use bert since its not a model, just find a good architecture and create a new notebook for it @ishaan-bhandari

**Comment by AdithyaP7** [comment]
https://blog.insightdatascience.com/using-bert-for-state-of-the-art-pre-training-for-natural-language-processing-1d87142c29e7

**Comment by AdithyaP7** [comment]
https://skimai.com/fine-tuning-bert-for-sentiment-analysis/

**Comment by ayaanzhaque** [comment]
https://stackabuse.com/python-for-nlp-movie-sentiment-analysis-using-deep-learning-in-keras/
