### ISSUE TITLE
Order of Models

### ISSUE THREAD

**Issue by ayaanzhaque** [ayaanzhaque/SuiSense#54]
1. Standard depression vs suicide model
2. Model that compares old texts (depression vs casual convo)
3. Progression Model

**Comment by viraajreddi** [comment]
1. https://suisense.pythonanywhere.com/standard
2. https://suisense.pythonanywhere.com/progression
3. https://suisense.pythonanywhere.com/advancedprogression

**Comment by ayaanzhaque** [comment]
Done with order, change up the text and make it finalized
